{% set version = '3.11.0' %}
{% set sha256 = '58f4f57ac96ec39273906859cdc388b1ae372045c726bfd2a01d4eca8bc4a1e6' %}

package:
  name: petsc4py
  version: {{version}}

source:
  fn: petsc4py-{{version}}.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 1
  script: PETSC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{mpi}}
    - petsc {{version.rsplit('.', 1)[0]}}.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{mpi}}
    - petsc # pinned by petsc run_exports

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
