{% set build = 1 %}
{% set version = '3.8.1' %}
{% set sha256 = 'd7b72c3337ddc56031d39d0b52d7f28b61ecc41b755ae853d23f34912b4f3c92' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}

package:
  name: petsc4py
  version: {{version}}

source:
  fn: petsc4py-{{version}}.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-{{version}}.tar.gz
  sha256: {{sha256}}
  patches:
    - 0001.patch
    - 0002.patch

build:
  number: {{build}}
  script: PETSC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - python
    - pip
    - numpy 1.8.*
    - {{mpi}}
    - petsc {{version[:3]}}*
  run:
    - python
    - numpy >=1.8
    - {{mpi}}
    - petsc {{version[:3]}}*

test:
  imports:
    - petsc4py
    - petsc4py.PETSc

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
