{% set version = '3.9.0' %}
{% set sha256 = 'cfe4ffa315706a371ca54e2027b4a8df8d696df253ab5ae7c0dbe5eccfa221e4' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}

package:
  name: petsc4py
  version: {{version}}

source:
  fn: petsc4py-{{version}}.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: 0
  script: PETSC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - python
    - pip
    - numpy 1.8.*
    - {{mpi}}
    - petsc {{version[:3]}}*
  run:
    - python
    - numpy >=1.8
    - {{mpi}}
    - petsc {{version[:3]}}*

test:
  imports:
    - petsc4py
    - petsc4py.PETSc

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
