travis:
  secure:
    BINSTAR_TOKEN: CJzG5KMrpB3YEkNKdkCua/BBdMrteEdV2Zufo6kR25fNeZhPit6UCj1VJVar2Rwar9r7+X7TAKdSaEEGPQoAFBi2ABdkM3i5gI3/tWsw3aGJYE9+TLYRjQaADiutcRVYyRRvsWFZUUCDeF5fIhkrAKbVQFVvCZ2I6nPYBsGgbe+Ju4pVTO1UVZXZzrA22OA2RcHg8iggcMpi7jCadYhOa2WgR0ypBM6+ZSuJgjAXbIopfl+dsZ5mZiPu2k/HQlvnafOmSRLgaKHOQYohm3GMdxdSCRz++iBqcWbVnrWguWIbh6/nuNEubUjsnWigjHYee4o4PJkMOpTV0KRqoekITbosE9AO6hkU2d/BI8c5b09ijshELMUKNcSLzVSozHD/aVc05+weShraiiggG9n6KA8EYRIVBI4zkYfnD/BG08F4Io2Jq2UmTFybkneq8R5jp8ylO9s5qGXtWKSpoxd18UFUgUMzQA18LmtG69PEA74pINU214YRRA2Ayk+zlRdEKwuu3qTzWtCp6I2TtkJIjVgU3mQU78ps2NOJftJ3rbXBLPRmkO/3CAHQc3l0gA8oOZSJthQjZxCL1luFvuEXPecP6lf7Hi+iEIex+VvXEUEXyFN0/EMIpBvUaEbyreOaPF3ksaZDIQTh4hUmkDl4lxr0GROCAp7JkH0PXvRb7Ek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
